name: "boinkor.net CI/go - lint"
description: "Run `golangci-lint` in the repository."
author: "Andreas Fuchs <asf@boinkor.net>"
inputs:
  module_base:
    description: "Directory containing the go.mod of the codebase under test"
    default: "."
  go_version:
    description: "Go toolchain to use. If unspecified, will use the version given in go.mod in module_base."
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up go toolchain
      uses: actions/setup-go@v5
      with:
        go-version: ${{inputs.go_version}}
        go-version-file: ${{inputs.module_base}}/go.mod
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      id: lint
      with:
        version: "v1.61.0"
        working-directory: ${{inputs.module_base}}
