name: "CI/Go - build"
on:
  workflow_call:
    inputs:
      module_base:
        description: "Directory containing the go.mod of the codebase under test"
        type: string
        default: "."
      go_version:
        description: "Go toolchain to use. If unspecified, will use the version given in go.mod in module_base."
        type: string
      subdir:
        description: "Directory containing the main.go of the executable being built"
        type: string
        default: "."

      # Used for testing this repo:
      _internal_continue_on_error:
        description: "Whether to set continue-on-error on the job; set this to true only in the tests _inside this repo_. Otherwise your workflow run will pass when it shouldn't."
        type: boolean

    outputs:
      _internal_build_result:
        description: "Result of the build job"
        value: ${{ jobs.build.outputs.result }}

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{inputs._internal_continue_on_error}}
    outputs:
      result: ${{steps.build.outcome}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/build
        with:
          module_base: ${{inputs.module_base}}
          go_version: ${{inputs.go_version}}
          subdir: ${{inputs.subdir}}
