name: "CI/Go - lints"
on:
  workflow_call:
    inputs:
      module_base:
        description: "Directory containing the go.mod of the codebase under test"
        type: string
        default: "."
      go_version:
        description: "Go toolchain to use. If unspecified, will use the version given in go.mod in module_base."
        type: string

      # Used for testing this repo:
      _internal_continue_on_error:
        description: "Whether to set continue-on-error on the job; set this to true only in the tests _inside this repo_. Otherwise your workflow run will pass when it shouldn't."
        type: boolean

    outputs:
      _internal_lint_result:
        description: "Result of the golangci_lint job"
        value: ${{ jobs.lint.outputs.result }}

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: ${{inputs._internal_continue_on_error}}
    outputs:
      result: ${{steps.lint.outcome}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{inputs.go_version}}
          go-version-file: ${{inputs.module_base}}/go.mod
      - name: golangci-lint
        id: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.61.0"
          working-directory: ${{inputs.module_base}}
