name: "Tests for this repo"
on:
  workflow_call:

jobs:
  success_tests:
    uses: "./.github/workflows/ci_baseline_go_tests.yml"
    with:
      module_base: "tests/success"

  success_lints:
    uses: "./.github/workflows/ci_baseline_go_lints.yml"
    with:
      module_base: "tests/success"

  success_build:
    uses: "./.github/workflows/ci_baseline_go_build.yml"
    with:
      module_base: "tests/success"
      subdir: "./cmd/hello-world"

  # Test jobs that expect failure:
  test_failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/test
        with:
          module_base: "tests/test-failure"
        continue-on-error: true
        id: failure
      - name: Expect failure
        run: |
          echo "::error title=Expected the failure step to fail::Instead: ${{steps.failure.outcome}}"
          exit 1
        if: ${{ failure() && steps.failure.outcome == 'failure' }}

  build_failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/build
        with:
          module_base: "tests/build-failure"
        id: failure
        continue-on-error: true
      - name: Expect failure
        run: |
          echo "::error title=Expected the failure step to fail::Instead: ${{steps.failure.outcome}}"
          exit 1
        if: ${{ failure() && steps.failure.outcome == 'failure' }}

  lint_fmt_failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/lint
        with:
          module_base: "tests/fmt-failure"
        id: failure
        continue-on-error: true
      - name: Expect failure
        run: |
          echo "::error title=Expected the failure step to fail::Instead: ${{steps.failure.outcome}}"
          exit 1
        if: ${{ failure() && steps.failure.outcome == 'failure' }}

  lint_failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/lint
        with:
          module_base: "tests/lint-failure"
        id: failure
        continue-on-error: true
      - name: Expect failure
        run: |
          echo "::error title=Expected the failure step to fail::Instead: ${{steps.failure.outcome}}"
          exit 1
        if: ${{ failure() && steps.failure.outcome == 'failure' }}

  # Testing that we pass the go_version argument through (by failing
  # the build on the wrong one):
  test_failure_version_mismatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/test
        with:
          go_version: "1.18"
          module_base: "tests/go1.20"
        continue-on-error: true
        id: failure
      - name: Expect failure
        run: |
          echo "::error title=Expected the failure step to fail::Instead: ${{steps.failure.outcome}}"
          exit 1
        if: ${{ failure() && steps.failure.outcome == 'failure' }}

  build_failure_version_mismatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/build
        with:
          go_version: "1.18"
          module_base: "tests/go1.20"
        continue-on-error: true
        id: failure
      - name: Expect failure
        run: |
          echo "::error title=Expected the failure step to fail::Instead: ${{steps.failure.outcome}}"
          exit 1
        if: ${{ failure() && steps.failure.outcome == 'failure' }}

  version_tests:
    uses: "./.github/workflows/ci_baseline_go_tests.yml"
    with:
      module_base: "tests/go1.20"

  version_lints:
    uses: "./.github/workflows/ci_baseline_go_lints.yml"
    with:
      module_base: "tests/go1.20"

  version_build:
    uses: "./.github/workflows/ci_baseline_go_build.yml"
    with:
      module_base: "tests/go1.20"
      subdir: "./cmd/hello-world"
